config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :leagues, only: [:index]
  resources :formats, only: [:index]
  resources :clubs, only: [:index]
  resources :contests, only: [:index, :new, :create, :edit, :update]
  resources :results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  belongs_to :league
  has_many :results
end

app/models/club.rb
class Club < ApplicationRecord
  belongs_to :league
  has_many :members
end

app/models/contest.rb
class Contest < ApplicationRecord
  belongs_to :user
  belongs_to :league

  has_and_belongs_to_many :formats
  has_many :results
  has_many :members, through: :results

  validates :name, presence: true, length: {maximum: 60, minimum: 5}
  validates :location, presence: true, length: {maximum: 60, minimum: 3}
  validates :date, presence: true

end

app/models/format.rb
class Format < ApplicationRecord
  has_and_belongs_to_many :contests
end

app/models/league.rb
class League < ApplicationRecord
  has_many :users
  has_many :clubs
  has_many :contests
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :club
  has_many :results
  has_many :contests, through: :results
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :contest
  belongs_to :calculation
  belongs_to :member

  has_many :calculations

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :league
  has_many :contests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def configure_permitted_parameters

    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :league_id])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname, :league_id])
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @clubs = Club.all
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  skip_before_action :authenticate_user!, only: []
  before_action :find_contest, only: [:edit, :update]

  def index
    @contests = Contest.where(league_id: current_user.league_id)
  end

  def new
    @contest = Contest.new
  end

  def create
    @contest = Contest.new(contest_params)
    if @contest.save
      redirect_to contests_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @contest.update(contest_params)
    if @contest.save
      redirect_to contests_path
    else
      render :edit
    end
  end

private
  def contest_params
    params.require(:contest).permit(
      :name,
      :location,
      :date,
      :user_id,
      :league_id,
      format_ids:[])
  end

  def find_contest
    @contest = Contest.find(params[:id])
  end

end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @formats = Format.all
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @leagues = League.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @results = Result.all
  end

  def new
    @result = Result.new
    @results = Result.where(contest_id: 96)
  end

  private
  def method_name

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clubs/index.html.erb
<div class="container">
  <h1>Liste des clubs de la LNA</h1>
  <% @clubs.each do |club| %>
    <div >
      <%= club. name %>| <%= club.postal_code %>
    </div>
  <% end %>
</div>

app/views/contests/_form_contest.html.erb
  <%= simple_form_for(@contest) do |f| %>
    <%= f.error_notification %>
    <%= f.input :name, label: "Nom de l'épreuve" %>
    <%= f.input :location, label: "Lieu de l'épreuve" %>
    <%= f.input :date %>
    <%= f.input :user_id, input_html: {value: current_user.id}, as: :hidden %>
    <%= f.input :league_id, input_html: {value: current_user.league.id}, as: :hidden %>
    <%= f.input :format_ids, collection: Format.all, as: :check_boxes, label: "Choisissez les formats" %>
    <%= f.submit 'Enregistrer', class: "btn btn-danger btn-block" %>
  <% end %>

app/views/contests/edit.html.erb
<div class="container">
  <h3>Mise à jour d'une épreuve</h3>
  <%= render 'form_contest' %>
</div>

app/views/contests/index.html.erb
<div class="container">
  <h1>Liste des courses</h1>
  <% if user_signed_in? %>
    <h2>League <%= current_user.league.name %></h2>
  <% end %>


  <div class="row">
    <% @contests.each do |contest| %>
      <div class="col-12 col-sm-6 col-md-4 ">
        <div class="contest-card box-shadow-shared">
          <div class="contest-card-name">
            <%= contest.name.upcase %>
          </div>
          <p>
            <i class="fas fa-map-marker-alt"></i>
            <%= contest.location %>
          </p>
          <p>
            <i class="far fa-calendar-alt"></i>
            <%= l contest.date, format: '%A %d %B' %>
          </p>
          <p><%= contest.league.name %></p>
          <p>
            Créateur : <%= contest.user.firstname %> <%= contest.user.lastname %>
          </p>
          <div class="contest-card-formats-content">
            <% contest.formats.each do |format| %>
              <div class="contest-card-formats box-shadow-shared">
                <%= format.name %>
              </div>
            <% end %>
          </div>
          <%= link_to edit_contest_path(contest.id), class:'btn btn-primary btn-block' do %>
            Modifier
          <% end %>
        </div>

      </div>
    <% end %>
  </div>

</div>

app/views/contests/new.html.erb
<div class="container">
  <h3>Création d'une épreuve</h3>
  <%= render 'form_contest' %>

</div>

app/views/formats/index.html.erb
<div class="container">
  <h1>Liste des formats</h1>
   <div class="row">
    <ul>
       <% @formats.each do |format_name| %>
       <li>
         <%= format_name.name %>
       </li>
       <% end %>
    </ul>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Challenge Triathlon</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/leagues/index.html.erb
<div class="container">
  <h3>Liste des ligues de Triathlon</h3>
  <% @leagues.each do |league| %>
    <p>
      <%= league.name %>
    </p>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Challenge Triathlon 2020</h1>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <%= link_to leagues_path, class: "btn btn-primary btn-block" do %>
          Liste des leagues de Triathlon
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <%= link_to clubs_path, class: "btn btn-primary btn-block" do %>
          Liste des clubs de la FFTRI
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <%= link_to formats_path, class: "btn btn-primary btn-block" do %>
          Liste des formats
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <div class="btn btn-danger btn-block">
          Importer des licenciés (admin)
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <%= link_to new_contest_path, class: "btn btn-primary btn-block" do%>
          Créer une course
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <%= link_to contests_path, class: "btn btn-primary btn-block" do %>
          Liste des courses
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <div class="btn btn-secondary btn-block">
          Régles de calculs
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <div class="btn btn-secondary btn-block">
          Importer des résultats
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <div class="btn btn-secondary btn-block">
          Saisir des résultats
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="homepage-card">
        <div class="btn btn-secondary btn-block">
          Afficher des résultats
        </div>
      </div>
    </div>
  </div>
</div>

app/views/results/index.html.erb
<div class="container">
  <h3>Résultats</h3>
  <% @results.each do |result| %>
    <p>
      <%= result.inspect %>
    </p>
  <% end %>

</div>

app/views/results/new.html.erb
<div class="container">
  <h3>Saisir les résultats d'une course</h3>

  <%= simple_form_for @result do |f| %>
    <%= f.error_notification %>
    <%= f.input :contest_id, collection: Contest.all %>
    <%= f.input :calculation_id, collection: Calculation.all  %>
    <%= f.input :member_id, collection: Member.all %>
    <%= f.input :place, collection: 1..30 %>
    <%= f.submit %>

  <% end %>
  <h3>Résultats de cette course</h3>
  <% @results.each do |result| %>
    <p>
      <%= result.place %> |
      <%= result.member.lastname %> |
      <%= result.calculation.points %>
    </p>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>